loc2me\OfferBundle\Entity\Avatar:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        hash:
            type: string
            unique: true
            nullable: false
    oneToOne:
            Offer:
                targetEntity: loc2me\OfferBundle\Entity\Offer
                inversedBy: Avatar
                joinColumns:
                    offer_id:
                        referencedColumnName: id