loc2me\OfferBundle\Entity\Offer:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        wifiName:
            type: string
            nullable: false
        description:
            type: text
            nullable: true
