loc2me\OfferBundle\Entity\OfferLookUp:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        wifiName:
            type: string
            nullable: false
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
