loc2me\OfferBundle\Entity\OfferLookUp:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        wifiName:
            type: string
            nullable: false
