loc2me\OfferBundle\Entity\Offer:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        wifiName:
            type: string
            nullable: false
        name:
            type: string
            nullable: false
        organizationName:
            type: string
            nullable: false
        description:
            type: text
            nullable: true
        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    oneToOne:
            Image:
                targetEntity: loc2me\OfferBundle\Entity\Image
                mappedBy: Offer
                cascade:
                    - all
    oneToOne:
            Avatar:
                targetEntity: loc2me\OfferBundle\Entity\Image
                mappedBy: Offer
                cascade:
                    - all
    manyToMany:
        Lookups:
            targetEntity: OfferLookup
            mappedBy: Offers
    manyToOne:
        User:
            targetEntity: loc2me\UserBundle\Entity\User
            inversedBy: Offers
            joinColumn:
                name: user_id
                referencedColumnName: id